version: '3.8'

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/sonarr:/config
      - ./downloads:/downloads
      - ./tv:/tv
    ports:
      - "8989:8989"
    restart: unless-stopped
