services:
  sillytavern:
    image: ghcr.io/sillytavern/sillytavern:latest
    environment:
      TZ: ${HOME_SERVER_TZ}
    volumes:
      - silly-tavern-plugins:/home/node/app/plugins
      - ./config:/home/node/app/config
      - silly-tavern-data:/home/node/app/data
    restart: unless-stopped
    ports:
      - 9999:8000/tcp
    networks:
      - traefik-net
      - macvlan-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  silly-tavern-data:
  silly-tavern-plugins: