services:
  sillytavern:
    image: ghcr.io/sillytavern/sillytavern:latest
    environment:
      TZ: ${HOME_SERVER_TZ}
    volumes:
      - silly-tavern-plugins:/home/node/app/plugins
      - ./config:/home/node/app/config
      - silly-tavern-data:/home/node/app/data
    restart: unless-stopped
    networks:
      - ${TRAEFIK_NETWORK}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}.${HOME_SERVER_DOMAIN}`) || Host(`${APP_DOMAIN}.localhost`)"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
      - "traefik.docker.network=${STACK_NAME}_${TRAEFIK_NETWORK}"
      - "homepage.group=GenAI Applications" # Group for this service on the homepage
      - "homepage.name=SillyTavern" # Name of this service on the homepage
      - "homepage.icon=openai.png" # Pick from https://github.com/homarr-labs/dashboard-icons
      - "homepage.href=http://${APP_DOMAIN}.${HOME_SERVER_DOMAIN}/" # Link to access this service on the homepage
      - "homepage.description=LLM interface for power users" # Description of this service on the homepage
      - "nautical-backup.override-source-dir=${STACK_NAME}_silly-tavern-data"
      - "nautical-backup.additional-folders=${STACK_NAME}_silly-tavern-plugins"

volumes:
  silly-tavern-data:
  silly-tavern-plugins:
