# Expanding foundation stack to include DNS server support with PiHole

include:
  - path: "../Foundation-Local/compose.yml" ## Foundation stack
  - path: "../../Apps/PiHole/compose.yml" ## App with custom envs
    env_file:
       - ../../Apps/PiHole/default.env
