services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    # container_name: homepage
    # ports:
    #   - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    environment:
      HOMEPAGE_ALLOWED_HOSTS: ${APP_DOMAIN}.${HOME_SERVER_DOMAIN},${APP_DOMAIN}.localhost # required, may need port. See gethomepage.dev/installation/#homepage_allowed_host
      # PUID: 1000 # optional, your user id
      # PGID: 1000 # optional, your group id
    restart: unless-stopped
    networks:
      - traefik-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}.${HOME_SERVER_DOMAIN}`) || Host(`${APP_DOMAIN}.localhost`)"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
