# This stack creates a "lab" for working with data. It provides the utilities to inject and perform exploratory data analysis. The stack includes the following utilities:
# - metabase (at metabase.localhost): no-code business intelligence tool
# 
#
include:
  - path: "../../Apps/Metabase/compose.yml" ## App with custom envs
    env_file:
       - ../../Apps/Metabase/default.env
  - path: "../../Apps/Jupyter/compose.yml" ## App with custom envs
    env_file:
       - ../../Apps/Jupyter/default.env
