services:
  metabase:
    image: metabase/metabase:latest
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    # ports:
      # - 3000:3000
    expose:
      - 3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
      MB_SITE_URL: "http://${APP_DOMAIN}.${HOME_SERVER_DOMAIN}"
    networks:
      - ${TRAEFIK_NETWORK}
      - metabase-net
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}.${HOME_SERVER_DOMAIN}`) || Host(`${APP_DOMAIN}.localhost`)"
      # - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
      - "traefik.docker.network=${STACK_NAME}_${TRAEFIK_NETWORK}"
      - "homepage.group=Data Analytics" # Group for this service on the homepage
      - "homepage.name=Metabase" # Name of this service on the homepage
      - "homepage.icon=metabase.png" # Pick from https://github.com/homarr-labs/dashboard-icons
      - "homepage.href=http://${APP_DOMAIN}.${HOME_SERVER_DOMAIN}/" # Link to access this service on the homepage
      - "homepage.description=Self-served BI" # Description of this service on the homepage

  postgres:
    image: postgres:latest
    hostname: metabase-pg
    volumes:
      - metabase-pg-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - metabase-net

  
volumes:
  metabase-pg-data:

networks:
  metabase-net:
