version: '3.8'

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config/openvpn:/etc/openvpn
    ports:
      - "1194:1194/udp"
    restart: unless-stopped
    networks:
      - traefik-net
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=1194"
networks:
  traefik-net:
    external: true
