version: '3.8'

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config/openvpn:/etc/openvpn
    ports:
      - "1194:1194/udp"
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openvpn.rule=Host(`openvpn.localhost`)"
      - "traefik.http.services.openvpn.loadbalancer.server.port=1194"
networks:
  traefik-net:
    external: true
