services:
  metube:
    image: alexta69/metube:2025-05-01
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - YTDL_OPTIONS={"cookiefile":"/cookies/cookies-youtube-com.txt"}
    volumes:
      - ${MEDIA_DIR}/Videos:/downloads
      # - ${METUBE_COOKIE_TXT_PATH}:/cookies/cookies-youtube-com.txt
    networks:
      - traefik-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}.${HOME_SERVER_DOMAIN}`) || Host(`${APP_DOMAIN}.localhost`)"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
      - "homepage.group=Media" # Group for this service on the homepage
      - "homepage.name=Metube" # Name of this service on the homepage
      - "homepage.icon=youtube.png" # Pick from https://github.com/homarr-labs/dashboard-icons
      - "homepage.href=http://${APP_DOMAIN}.${HOME_SERVER_DOMAIN}/" # Link to access this service on the homepage
      - "homepage.description=Youtube downloader" # Description of this service on the homepage
