dataRoot: ./data
listen: false
port: 8000
whitelistMode: false
enableForwardedWhitelist: true
whitelist:
  - 127.0.0.1
  - 0.0.0.0
basicAuthMode: true
basicAuthUser:
  username: gen
  password: gengen
enableCorsProxy: false
enableUserAccounts: false
enableDiscreetLogin: false
cookieSecret: E+JWU0q0n8DdopC8gOUFVFk31Nh85S2MSafKvwbTgY1lCjF839U8nuAV6KokQKPCju6uphaOFtAAGLnVdsFbJw==
disableCsrfProtection: false
securityOverride: false
autorun: true
disableThumbnails: false
thumbnailsQuality: 95
avatarThumbnailsPng: false
allowKeysExposure: false
skipContentCheck: false
disableChatBackup: false
numberOfBackups: 50
whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
requestOverrides: []
enableExtensions: true
extras:
  disableAutoDownload: false
  classificationModel: Cohee/distilbert-base-uncased-go-emotions-onnx
  captioningModel: Xenova/vit-gpt2-image-captioning
  embeddingModel: Cohee/jina-embeddings-v2-base-en
  promptExpansionModel: Cohee/fooocus_expansion-onnx
  speechToTextModel: Xenova/whisper-small
  textToSpeechModel: Xenova/speecht5_tts
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
enableServerPlugins: false
