version: '3.8'

services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/lidarr:/config
      - ./downloads:/downloads
      - ./music:/music
    ports:
      - "8686:8686"
    restart: unless-stopped
    networks:
      - traefik-net
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=8686"
networks:
  traefik-net:
    external: true
