version: '3.8'

services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/lidarr:/config
      - ./downloads:/downloads
      - ./music:/music
    ports:
      - "8686:8686"
    restart: unless-stopped
