version: "3.8"
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_HOSTNAME=${TS_HOSTNAME}
      - LAN_CIDR=${LAN_CIDR}
    entrypoint: >
      sh -c "tailscaled &
             exec tailscale up \
               --authkey=${TS_AUTHKEY} \
               --hostname=${TS_HOSTNAME} \
               --advertise-dns=$(tailscale ip -4) \
               --advertise-routes=${LAN_CIDR} \
               --accept-routes"
volumes:
  tailscale-data:
    driver: local
