services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_HOSTNAME=${STACK_NAME}-tailscale
      - TS_ROUTES=${LAN_CIDR}
    volumes:
      - tailscale-data:/var/lib/tailscale

volumes:
  tailscale-data:
    driver: local
