version: '3'
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    environment:
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    # network_mode: host
    networks:
      - ai_stack_network
      - macvlan_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sillytavern:
    image: ghcr.io/sillytavern/sillytavern:latest
    container_name: sillytavern
    ports:
      - "9999:8000/tcp"
    networks:
      - ai_stack_network
      - macvlan_network
    environment:
      TZ: ${ST_TZ}
    volumes:
      - silly-tavern-plugins:/home/node/app/plugins
      - ${ST_CONFIG}:/home/node/app/config
      - silly-tavern-data:/home/node/app/data
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    depends_on:
      - langflow-postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@langflow-postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
    volumes:
      - langflow-data:/app/langflow
    networks:
      - macvlan_network
    restart: unless-stopped

  langflow-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    networks:
      - macvlan_network
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "9090:8080"
    volumes:
      - ./searxng:/etc/searxng
    networks:
      - ai_stack_network
    restart: unless-stopped

volumes:
  langflow-postgres:
  langflow-data:
  open-webui:
  silly-tavern-data:
  silly-tavern-plugins:

networks:
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: wlp6s0
    ipam:
      config:
        - subnet: 10.42.0.0/24
          gateway: 10.42.0.1
          ip_range: 10.42.0.2/24
  ai_stack_network: