version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    labels:
      - traefik.enable=true
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_DOMAIN}.${HOME_SERVER_DOMAIN}`)"
      - 'traefik.http.services.pihole.loadbalancer.server.port=80'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '8053:80/tcp'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      FTLCONF_LOCAL_IPV4: 192.168.8.2
      WEBPASSWORD: '${PIHOLE_WEB_PASSWORD}'
    extra_hosts:
      # Resolve to nothing domains (terminate connection)
      - 'nw2master.bioware.com nwn2.master.gamespy.com:0.0.0.0'
      # LAN hostnames for other docker containers using nginx-proxy
      - 'bunbun.home:192.168.8.2'
      - 'pihole pihole.bunbun.home:192.168.8.2'
      - 'whoami whoami.bunbun.home:192.168.8.2'
    restart: always
    networks:
      - traefik-net