version: "3.8"
services:
    drone:
        image: drone/drone:2
        environment:
        - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
        - DRONE_SERVER_PROTO=http
        - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
        - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
        - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}