# Current stack of software of my office. It contains the following sub-stacks:
# - Foundation (routing and observability)
# - Persistence (postgres database)
# - Data-Analysis
# - GenAI Apps

name: ${STACK_NAME}

include:
  - path: "../../Substacks/Foundation-DNS/compose.yml" ## Foundation stack 
  - path: "../../Substacks/Troubleshooting/compose.yml" ## Compose Stack
  - path: "../../Substacks/Media/compose.yml" ## Compose Stack
  - path: "../../Substacks/GenAI-Apps/compose.yml" ## Compose Stack
