# Current stack of software of my office. It contains the following sub-stacks:
# - Foundation (routing and observability)
# - Persistence (postgres database)
# - Data-Analysis
# - GenAI Apps

name: ${STACK_NAME}

include:
  - path: "../Foundation/compose.yml" ## Foundation stack 
  - path: "../Media/compose.yml" ## Compose Stack
  - path: "../../Apps/PiHole/compose.yml" ## App with custom envs
    env_file:
       - ../../Apps/PiHole/default.env