services:
  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng
    ports:
      - 8888:8080
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"