# Foundation-DNS-TS expands the Foundation-DNS to provide Tailscale support
#
include:
  - path: "../Foundation-DNS/compose.yml" ## Foundation DNS stack with PiHole support
  - path: "../../Apps/Tailscale/compose.yml" ## Tailscale VPN and DNS
    env_file:
       - ../../Apps/Tailscale/default.env
