version: '3'

include:
  - path: ../Traefik/docker-compose.yml ## Traefik: reverse proxy
  - path: ../Traefik/docker-compose.yml ## Traefik: reverse proxy
  - path: ../PiHole/docker-compose.yml ## Pihole: DNS server and ad blocker
  - path: ../Metube/docker-compose.yml ## Metube: YouTube downloader
  - path: ../Jellyfin/docker-compose.yml ## Jellyfin: Media server
  - path: ../Mealie/compose.yaml ## Mealie: Menu planner server
  - path: ../CodeServer/compose.yaml ## Codeserver