---
version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.3.2 # 
    container_name: mealie
    deploy:
      resources:
        limits:
          memory: 1000M #
    ports:
      - 9999:9000
    dns:
      - 127.0.0.1
      - 1.1.1.1
    labels: ## Traefik configuration
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.rule=Host(`${MEALIE_DOMAIN}.${HOME_SERVER_DOMAIN}`)"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000" 
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      # - TZ=${HOME_SERVER_TZ}
      - TZ="Australia/Adelaide"
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=http://${MEALIE_DOMAIN}.${HOME_SERVER_DOMAIN}`
    restart: always
    networks:
      - traefik-net

volumes:
  mealie-data:
    driver: local