# Template for defining a new software stack.
# It includes the foundation stack and other necessary applications
#
include:
  - path: "../Foundation/compose.yml" ## Foundation stack 
  # - path: "../Persistence/compose.yml" ## Data persistence stack 
  # - path: ../Apps/App-Name-1/compose.yml ## App 1
  # - path: ../Apps/App-Name-2/compose.yml ## App 2
  - path: "../../Apps/Metube/compose.yml" ## Youtube downloader
    env_file:
       - ../../Apps/Metube/default.env
  - path: "../../Apps/Jellyfin/compose.yml" ## Media server
    env_file:
       - ../../Apps/Jellyfin/default.env
  - path: "../../Apps/Mealie/compose.yml" ## Food database server
    env_file:
       - ../../Apps/Mealie/default.env
