version: '3'
services:
  gpt-researcher:
    # pull_policy: build
    image: gentran1991/gpt-researcher:0.3.1
    build: ./
    environment: 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      SEARX_URL: http://searxng:8080
      RETRIEVER_ARG_SEARX_URL: http://searxng:8080
    restart: always
    ports:
      - 8888:8000
    networks:
      - ai-stack_macvlan_network
      - ai-stack_ai_stack_network
  gptr-nextjs:
    # pull_policy: build
    image: gentran1991/gptr-nextjs:0.3.1
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING = true
    build:
      dockerfile: Dockerfile.dev
      context: multi_agents/frontend
    volumes:
      - /app/node_modules
      - ./multi_agents/frontend:/app
    restart: always
    ports:
      - 3333:3000
    networks:
      - ai-stack_macvlan_network
      - ai-stack_ai_stack_network

networks:
  ai-stack_macvlan_network:
    external: true
  ai-stack_ai_stack_network:
    external: true
