services:
  langflow:
    image: langflowai/langflow:1.4.1
    depends_on:
      - langflow-postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@langflow-postgres:5432/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
    volumes:
      - langflow-data:/app/langflow
    restart: unless-stopped
    networks:
      - ${TRAEFIK_NETWORK}
      - langflow-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}.${HOME_SERVER_DOMAIN}`) || Host(`${APP_DOMAIN}.localhost`)"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
      - "traefik.docker.network=${STACK_NAME}_${TRAEFIK_NETWORK}"
      - "homepage.group=GenAI Tools" # Group for this service on the homepage
      - "homepage.name=Langflow" # Name of this service on the homepage
      - "homepage.icon=openai.png" # Pick from https://github.com/homarr-labs/dashboard-icons
      - "homepage.href=http://${APP_DOMAIN}.${HOME_SERVER_DOMAIN}/" # Link to access this service on the homepage
      - "homepage.description=Low-code LLM agent builder" # Description of this service on the homepage
      - "nautical-backup.group=langflow"
      - "nautical-backup.override-source-dir=${STACK_NAME}_langflow-data"

  langflow-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - langflow-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "nautical-backup.group=langflow"
      - "nautical-backup.override-source-dir=${STACK_NAME}_langflow-postgres"

volumes:
  langflow-postgres:
  langflow-data:

networks:
  langflow-net:
