services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    volumes:
      - ${MEDIA_DIR}/audiobooks:/audiobooks
      - ${MEDIA_DIR}/podcasts:/podcasts
      - audiobookshelf-config:/config
      - audiobookshelf-metadata:/metadata
    environment:
      - TZ=${HOME_SERVER_TZ}
    restart: unless-stopped
    networks:
      - ${TRAEFIK_NETWORK}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true" # Enable reverse proxy
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}.${HOME_SERVER_DOMAIN}`) || Host(`${APP_DOMAIN}.localhost`)" # Domain names to reach the app
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}" # Tell reverse proxy which port to use
      - "traefik.docker.network=${STACK_NAME}_${TRAEFIK_NETWORK}"
      - "homepage.group=Media" # Group for this service on the homepage
      - "homepage.name=Audio Book Shelf" # Name of this service on the homepage
      - "homepage.icon=audiobookshelf.svg" # Pick from https://github.com/homarr-labs/dashboard-icons
      - "homepage.href=http://${APP_DOMAIN}.${HOME_SERVER_DOMAIN}/" # Link to access this service on the homepage
      - "homepage.description=Audio book and podcasts" # Description of this service on the homepage
      - "nautical-backup.override-source-dir=${STACK_NAME}_audiobookshelf-config"
      - "nautical-backup.additional-folders=${STACK_NAME}_audiobookshelf-metadata"

volumes:
  audiobookshelf-config:
  audiobookshelf-metadata:
