services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      OLLAMA_BASE_URL: ${OPENWEBUI_OLLAMA_BASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ENABLE_WEB_SEARCH: True
      WEB_SEARCH_RESULT_COUNT: 3
      WEB_SEARCH_ENGINE: ${OPENWEBUI_WEB_SEARCH_ENGINE}
      SEARXNG_QUERY_URL: ${OPENWEBUI_SEARXNG_QUERY_URL}
      ENABLE_OAUTH_SIGNUP: true
      OAUTH_MERGE_ACCOUNTS_BY_EMAIL: true
      OAUTH_PROVIDER_NAME: Authentik
      OPENID_PROVIDER_URL: http://authentik.${HOME_SERVER_DOMAIN}/application/o/openwebui/.well-known/openid-configuration
      OAUTH_CLIENT_ID: ${OIDC_CLIENT_ID_OPENWEBUI}
      OAUTH_CLIENT_SECRET: ${OIDC_CLIENT_SECRET_OPENWEBUI}
      OAUTH_SCOPES: openid email profile
      OPENID_REDIRECT_URI: http://${APP_DOMAIN}.${HOME_SERVER_DOMAIN}/oauth/oidc/callback
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    # network_mode: host
    networks:
      - ${TRAEFIK_NETWORK}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}.${HOME_SERVER_DOMAIN}`) || Host(`${APP_DOMAIN}.localhost`)"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
      - "traefik.docker.network=${STACK_NAME}_${TRAEFIK_NETWORK}"
      - "homepage.group=GenAI Applications" # Group for this service on the homepage
      - "homepage.name=OpenWebUI" # Name of this service on the homepage
      - "homepage.icon=openai.png" # Pick from https://github.com/homarr-labs/dashboard-icons
      - "homepage.href=http://${APP_DOMAIN}.${HOME_SERVER_DOMAIN}/" # Link to access this service on the homepage
      - "homepage.description=Chatbot UI for LLMs" # Description of this service on the homepage

volumes:
  open-webui:
