services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    # network_mode: host
    ports:
      - 3000:8080
    networks:
      - traefik-net
      - macvlan-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  open-webui: