services:
  open-webui:
    # image: ghcr.io/open-webui/open-webui:main
    # environment:
    #   OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
    # volumes:
    #   - open-webui:/app/backend/data
    restart: unless-stopped
    networks:
      - traefik-net
      - macvlan-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}.${HOME_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}.localhost`)"
      # - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=PORT"

volumes:
  open-webui: